# -*- coding: utf-8 -*-
"""SSCD EXP 2 URK20CS2114.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kfYmkGpyYgiG81AnggKtMiHEEBAQBkw_
"""

i = input()
temp = i.split()
integer=[]
floating=[]
char=[]
double=[]
method=[]
variable=[]
constants=[]
constantVal = []
charVal=[]
datatype=['int','float','double','char']
parameterCount=[]
parameter=[]

def dtypes(x,y):
  if temp[x]=='int':
    integer.append(y)
  if temp[x]=='float':
    floating.append(y)
  if temp[x]=='double':
    double.append(y)
  if temp[x]=='char':
    char.append(y)

for i in range(len(temp)):
  if temp[i] in datatype:
    if temp[i+2] == '(':
      method.append(temp[i+1]) 
      dtypes(i, temp[i+1])
      p=0
      for j in range(i+2, len(temp)):
        if temp[j] == ',':
          p+=1
      parameterCount.append(p+1)
      vcount=0
    else:
      for j in range(i+1, len(temp)):
        if temp[j].isalpha():
          if temp[j] not in datatype:
            if temp[j] not in variable:
              if temp[j+1] == '='and temp[j+2].isnumeric():
                constants.append(temp[j])
                constantVal.append(temp[j+2])
                dtypes(i,temp[j])
                continue
              if temp[j-2] == '(' or temp[j+1] == ')':
                parameter.append(temp[j])
                continue
              if temp[j-2] == '=' and temp[j-3] in char:
                print(temp[j])
                charVal.append(temp[j])
                continue
              variable.append(temp[j])
              dtypes(i,temp[j])
              
        if temp[j] == ';':
          break

print("ID\t Data Type\t Return Type\t Initial Value\t No. of Parameters\t parameters")
c=0
p=0
v=0
ch=0
def Dtypes(x):
  print(x, end='\t  ')
  if x in integer:
    print('int', end='\t\t')
    return 'int'
  elif x in floating:
    print('float', end='\t\t')
  elif x in double:
    print('double', end='\t\t')
  elif x in char:
    print('char', end='\t\t')
    return 'char'
  
for i in temp:
  if i in variable:
    d = Dtypes(i)
    if d == 'int':
      print("\t\t\t","0")
    elif d=='char':
      print("\t\t\t",charVal[ch])
      ch+=1
  elif i in constants:
    Dtypes(i)
    print("\t\t\t",constantVal[v])
  elif i in method:
    print(i, end='\t\t\t  ')
    if i in integer:
      print('int', end='\t\t\t\t')
    elif i in floating:
      print('float', end='\t\t\t\t')
    elif i in double:
      print('double', end='\t\t\t\t')
    elif i in char:
      print('char', end='\t\t\t\t')
    print(parameterCount[p], end='\t\t  ')
    p+=1
    print(parameter[:-1])
    print()